### ISSUE TITLE
怎么不用 LetsEncrypt 加密 HTTP 呢？

### ISSUE THREAD

**Issue by donizyo** [Ehco1996/django-sspanel#2]
免费领取 HTTPS 证书，尽在 [LetsEncrypt](https://letsencrypt.org/)

**Comment by tabs** [comment]
hello i deploy it success but i get a 404 error when a test user click 签到 button
here error message
RelatedObjectDoesNotExist at /checkin/
User has no ss_user.
Request Method:	GET
Request URL:	http://leapfrog.top/checkin/
Django Version:	1.11.3
Exception Type:	RelatedObjectDoesNotExist
Exception Value:	
User has no ss_user.
Exception Location:	/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py in __get__, line 407
Python Executable:	/root/.pyenv/versions/3.6.1/bin/uwsgi
Python Version:	3.6.1

**Comment by Ehco1996** [comment]
@tabs 

this error because you did not binding user account with ss_user ,
it only happen when your create in django command line，
if user register in web，this won't happen

you can fix this by  following steps ：

* enter django admin  with your admin account
* add / binding your account  with ss_user (in ssserver area) 


------------------------------------------
英语不好，见谅

出现这个的原因是因为，你的账号是通过python manage.py createsuperuser 建立的
这样的账号，没有绑定到ssserver上，所以会报错，
走正常注册流程的账号则不会出现问题。

修复他你只需进入django的默认后台，将你的user账号绑定到ssserver里就可以了。

**有问题的话请独立开一个issues，不然会排版混乱**

**Comment by Ehco1996** [comment]
最后决定采用 https://certbot.eff.org 一件生成证书
